version: '3.8'

services:
  grafanatest:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    environment:
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
